In [1]:
import plotly.graph_objects as go
import pandas as pd

In [2]:
data = pd.read_csv('./data/mt_bruno_elevation.csv')
del data['index']

In [3]:
data.head()

0         1          2          3          4          5         6  \
0  27.809850  49.61936  83.080670  116.66320  130.41400  150.72060  220.1871   
1  27.719660  48.55022  65.213740   95.27666  116.99640  133.90560  152.3412   
2  30.426700  33.47752  44.809530   62.47495   77.43523  104.21530  102.7393   
3  16.665490  30.10860  39.969520   44.12225   59.57512   77.56929  106.8925   
4   8.815617  18.35160   8.658275   27.58590   48.62691   60.18013   91.3286   

          7         8         9    ...            14        15        16  \
0  156.1536  148.6416  203.7845    ...      49.96142  21.89279  17.02552   
1  151.9340  160.1139  179.5327    ...      33.08871  38.40972  44.24843   
2  137.0004  186.0706  219.3173    ...      48.47132  74.71461  60.09090   
3  166.5539  175.2381  185.2815    ...      60.55916  55.92124  15.17284   
4  145.7109  116.0653  106.2662    ...      47.42691  69.20731  44.95468   

          17         18         19         20         21         22         23  
0  11.743170  14.752260  13.667100   5.677561   3.312340   1.156517  -0.147662  
1  69.578600   4.019351   3.050024   3.039719   2.996142   2.967954   1.999594  
2   7.073525   6.089851   6.537450   6.666096   7.306965   5.736840   3.625628  
3   8.248324  36.680870  61.934130  20.268670  68.588190  46.498120   0.236009  
4  29.171970  17.916740  16.255150  14.655590  17.260480  31.222450  46.717040  

[5 rows x 24 columns]

In [4]:
height = data.values

In [ ]:
surface = go.Surface(z = height)
fig = go.Figure(surface)
fig.show()

## customized surface

In [5]:
import numpy as np

In [6]:
x = np.arange(-5, 6)
y = np.arange(-5, 6)

In [7]:
xv, yv = np.meshgrid(x, y)

In [8]:
xv

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5]])

In [9]:
yv

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

In [10]:
z = xv**2 + yv**2
z

array([[50, 41, 34, 29, 26, 25, 26, 29, 34, 41, 50],
       [41, 32, 25, 20, 17, 16, 17, 20, 25, 32, 41],
       [34, 25, 18, 13, 10,  9, 10, 13, 18, 25, 34],
       [29, 20, 13,  8,  5,  4,  5,  8, 13, 20, 29],
       [26, 17, 10,  5,  2,  1,  2,  5, 10, 17, 26],
       [25, 16,  9,  4,  1,  0,  1,  4,  9, 16, 25],
       [26, 17, 10,  5,  2,  1,  2,  5, 10, 17, 26],
       [29, 20, 13,  8,  5,  4,  5,  8, 13, 20, 29],
       [34, 25, 18, 13, 10,  9, 10, 13, 18, 25, 34],
       [41, 32, 25, 20, 17, 16, 17, 20, 25, 32, 41],
       [50, 41, 34, 29, 26, 25, 26, 29, 34, 41, 50]])

In [ ]:
surface = go.Surface(x = xv, y = yv, z = z)
fig = go.Figure(surface)
fig.show()